DEBUG = True
PROPAGATE_EXCEPTIONS = True
TESTING = True
HAPI_TEST = False
TESTL = 7
DBNAME = "test_sehas_shells.sq"
API_TITLE = "SHELLS REST API"
API_VERSION = "v1"
OPENAPI_VERSION = "3.0.3"
OPENAPI_URL_PREFIX = "/"
OPENAPI_SWAGGER_UI_PATH = "/swagger-ui"
OPENAPI_SWAGGER_UI_URL = "https://cdn.jsdelivr.net/npm/swagger-ui-dist/"
